### ISSUE TITLE
Question: "<100"

### ISSUE THREAD

**Issue by franciscolourenco** [hypeserver/impferator#4]
Hi @yigitbey, thank you for writing this script.

I'm curious, why do you exclude availabilities with more than 100?
![image](https://user-images.githubusercontent.com/208149/119871195-810f7800-bf22-11eb-873a-ce1a3aa11f68.png)

**Comment by keremciu** [comment]
> Hi @yigitbey, thank you for writing this script.
> 
> I'm curious, why do you exclude availabilities with more than 100?
> ![image](https://user-images.githubusercontent.com/208149/119871195-810f7800-bf22-11eb-873a-ce1a3aa11f68.png)

it's weird data because doctolibs availability :/

**Comment by franciscolourenco** [comment]
thanks!
